### ISSUE TITLE
Improving footer 

### ISSUE THREAD

**Issue by Bhavya-C-ai** [codemaniac-sahil/random_jokes#16]
I noticed how all three social media icons have different hover behaviour and looks misaligned:
![image](https://user-images.githubusercontent.com/96719986/193975313-0f1e46c9-15de-4b9e-859d-38a875ecdeca.png)
I'm thinking of making it something like:
![image](https://user-images.githubusercontent.com/96719986/193975891-6bf47894-5bc5-45fb-abfe-651e846849fd.png)
They will show their true colors when hovered :)
Can this issue be assigned to me under hacktober label?

**Comment by codemaniac-sahil** [comment]
great @Bhavya-C-ai start working on it. I am assigning this case to you.

**Comment by codemaniac-sahil** [comment]
actually those social icons are for sharing the joke

**Comment by codemaniac-sahil** [comment]
but you can work on the footer section

**Comment by codemaniac-sahil** [comment]
You did great @Bhavya-C-ai
