### ISSUE TITLE
Improving the font styling and other UI changes

### ISSUE THREAD

**Issue by floating-dynamo** [codemaniac-sahil/random_jokes#28]
Hi Sahil,

I can make the website look a bit better, can you assign it to me?

**Comment by codemaniac-sahil** [comment]
@floating-dynamo you can start working on this issue

**Comment by floating-dynamo** [comment]
Thank you!

**Comment by tanyaa-arora** [comment]
@floating-dynamo I'd like to work on this task. Kindly assign it to me
